Bump version to 3.0
open-switch/opx-core pull request #7
Opened 2018-08-16 22:12 UTC by GarrickHe

* Bump OS_VERSION to 3.0.0
* Update postinst script

Signed-off-by: Garrick He <garrick_he@dell.com>

2018-08-16 22:37 UTC, heucke requested changes
Please fix the commit message. The subject says 3.0, but the body says 3.0.0. Which is it?

2018-08-17 00:42 UTC, atanu-mandal submitted a review, later dismissed

2018-08-17 16:42 UTC, GarrickHe commented
Pull-request updated, HEAD is now 91843c256584fd0cd422b8dceefe6f3121a449ef

2018-08-17 17:10 UTC, heucke approved these changes

2018-08-17 20:41 UTC, hpersh approved these changes

2018-08-17 20:42 UTC, merged